export default {
  appName: 'G-Gastos',
  currentBalance: 'Saldo Atual',
  expectedBalance: 'Saldo Esperado',
  currentSpend: 'Gasto Atual',
  expectedSpend: 'Gasto Esperado',
  value: 'Valor',
  date: 'Data',
  installments: 'Parcelas',
  selectCategory: 'Categoria',
  title: 'Título',
  repeatTimes: 'Parcelas',
  description: 'Descrição',
  paymentType: 'Tipo de pagamento',
  yearConsolidated: 'Ano Consolidado',
  repeat: 'Repetir',
  save: 'Salvar',
  cancel: 'Cancelar',
  loading: 'Carregando...',
  configuration: 'Configurações',
  selectTheYear: 'Selecione o ano',
  newItem: 'Novo Item',
  storage: {
    getItemsError: 'Erro ao obter itens do AsyncStorage:',
    saveError: 'Erro ao salvar itens no AsyncStorage:',
    clearError: 'Erro ao limpar AsyncStorage:',
    deleteError: 'Erro ao remover item do AsyncStorage:',
  },
};
