export default {
  appName: 'G-Gastos',
  currentBalance: 'Saldo Atual',
  expectedBalance: 'Saldo Esperado',
  currentSpend: 'Gasto Atual',
  expectedSpend: 'Gasto Esperado',
  value: 'Valor',
  date: 'Data',
  installments: 'Parcelas',
  selectCategory: 'Selecione uma categoria',
  title: 'Título',
  repeatTimes: 'Num de parcelas',
  description: 'Descrição',
  yearConsolidated: 'Ano Consolidado',
  repeat: 'Repetir',
  save: 'Salvar',
  cancel: 'Cancelar',
  loading: 'Carregando...',
  configuration: 'Configurações',
  selectTheYear: 'Selecione o ano',
  newItem: 'Novo Item',
};
